dist: trusty
language: ruby
cache: bundler
sudo: false

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13

env:
  - DB=postgresql
  global:
  - PGPORT=5432

rvm:
  - 2.7

before_script:
  - cp config/database.travis config/database.yml
  - psql -c 'CREATE DATABASE escamboapp_test;' -U postgres

script:
  - gem update --system
  - gem install bundler
  - bundle install --jobs $(nproc)
  - export RAILS_ENV=test
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rails test
