language: ruby
cache: bundler
sudo: false

env:
  - DB=postgresql
  - DB=mysql
  - DB=sqlite3

rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0

before_script:
  - psql -c 'CREATE DATABASE brimir_test;' -U postgres
  - mysql -e 'create database brimir_test;'
  - cp config/database.travis config/database.yml
  - bundle exec rake db:migrate