dist: trusty
language: ruby
cache: bundler
sudo: false

addons:
  postgresql: 9.6

env:
  - DB=postgresql

rvm:
  - 2.4.1

before_script:
  - cp config/database.travis config/database.yml
  - psql -c 'CREATE DATABASE escamboapp_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake test
