os: linux
language: ruby
dist: bionic

rvm:
  - 2.7.1

services:
  - postgresql

env:
  global:
    - DB=postgresql

bundler_args: --path=vendor/bundle --jobs $(nproc)
cache: bundler

before_script:
  - cp config/database.travis config/database.yml
  - psql -c 'CREATE DATABASE escamboapp_test;' -U postgres

script:
  - gem update --system
  - gem install bundler
  - bundle check || bundle install
  - export RAILS_ENV=test
  - bundle exec rails db:schema:load
  - bundle exec rails db:migrate
  - bundle exec rails test
