language: ruby

env:
  global:

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v
  - docker-compose config
  - cp sample.env .env

install:
  - docker-compose build

before_script:
  - docker-compose run --rm --no-deps escambo_app echo 'Gems now pre-installed.'
  - docker-compose up -d
  - docker ps
  - docker-compose run --no-deps escambo_app bundle exec rake db:migrate
  - docker-compose run --no-deps escambo_app bundle exec rake db:create RAILS_ENV=test
  - docker-compose run --no-deps escambo_app bundle exec rake db:migrate RAILS_ENV=test

script:
  - docker-compose run --no-deps escambo_app bundle exec rails test

after_script:
  - docker-compose down
