language: ruby

services:
  - docker

env:
  global:
    - RAILS_ENV=test

before_install:
  - cp ./sample.env ./.env

install:
  - docker-compose build

before_script:
  - cp ./sample.env ./.env
  - docker-compose up -d
  - docker ps -a --format "table{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.RunningFor}}"
  - docker exec -it escambo_app bundle check || bundle install
  - docker exec -it escambo_app bundle exec rails db:schema:load --trace

script:
  - docker exec -it escambo_app bundle exec rails test

after_script:
  - docker-compose down
