version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    logging:
      driver: "none"
    env_file: [".env"]
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    env_file: [".env"]
    depends_on: ['postgres']
    build: .
    command: bash start.sh
    ports: ['3099:3000']
    volumes: ['.:/escamboApp']
    volumes_from: ['box']

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: