version: "2"

services:
  postgres:
    image: "postgres:9.5"
    logging:
      driver: "none"
    env_file: [".env"]
    volumes: [ "postgres:/var/lib/postgresql/data" ]

  escambo_app:
    image: escambo_app:latest
    container_name: escambo_app
    build: .
    env_file: [".env"]
    depends_on: ["postgres"]
    command: sh start.sh
    ports: ["3099:3000"]
    volumes: [".:/escamboApp", ".gems_escambo:/.gems_escambo"]

volumes:
  postgres:
  .gems_escambo: