version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  test:
    parallelism: 2
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          RAILS_ENV: test
          DB_USER: root
          DB_HOST: 127.0.0.1
          DB_PREFIX: escambo
          DB_PASS: postgres
          DB_PORT: 5432
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: escambo_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: run tests
          command: bundle exec rails test
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
          destination: reports

workflows:
  version: 2
  test:
    jobs:
      - test
