default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  user: <%= ENV['DATABASE_USER'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_test


production:
  <<: *default
  database: <%= ENV['DATABASE_PREFIX'] %>_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
