default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: <%= ENV['DB_PREFIX'] %>_development

test:
  <<: *default
  database: <%= ENV['DB_PREFIX'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_PREFIX'] %>